use_frameworks!

target 'PolarKit_Example' do
  platform :ios, 10
  pod 'PolarKit', :path => '../'
end

target 'PolarKit_Tests' do
  platform :ios, 10

  pod 'PolarKit', :path => '../'

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
