osx_image: xcode7.3
language: objective-c
xcode_workspace: Example/PolarKit.xcworkspace
xcode_scheme: PolarKit-Example
xcode_sdk: iphonesimulator

before_install:
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/PolarKit.xcworkspace -scheme PolarKit-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
